accelerator: gpu
batch_size: 16
check_val_every_n_epoch: 1
ckpt_every_n_epoch: 1
data_augmentation: False
datamodule: civilcomments
devices: 1
lr: 1e-5
lr_scheduler: linear
max_epochs: 10
metrics: ["loss", "acc", "acc_by_group"]
model: bert
optimizer: adamw
strategy: ddp_spawn_find_unused_parameters_false
