accelerator: gpu
batch_size: 256
check_val_every_n_epoch: 10
ckpt_every_n_epoch: 10
cnn_initial_width: 16
cnn_num_layers: 3
data_augmentation: False
datamodule: mnist
devices: 1
input_channels: 1
lr: 0.1
max_epochs: 10
model: cnn
